# Generated by Django 6.0.4 on 2026-04-09 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservations',
            new_name='Booking',
        ),
    ]
